data:
  base_path: 'data/'
  data_path: 'apple2orange/'
  processed_path: 'processed_data/'
  imageX_path: 'trainA'
  imageY_path: 'trainB'

model:
  base_generator_filter: 64
  base_discriminator_filter: 64
  image_size: 256
  cycle_loss_weight_X: 10.0
  cycle_loss_weight_Y: 10.0
  real_label: 0.9
  gen_images_buffer_size: 50

train:
  batch_size: 1
  generator_train_step: 1
  model_dir: 'logs/cycleGAN'

  learning_rate: 0.0002
  start_decay_step: 100000
  beta1: 0.5

  max_steps: 200000
  save_checkpoints_steps: 2000
  check_hook_n_iter: 100

  debug: False

predict:
  model: 'G'
